SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population]
      ,[new_vaccinations]
      ,[AddedVaccinatedPeople]
  FROM [PersonalProject].[dbo].[PercentPopulationVacccinated]
